"""``tda gtfs``: list feed versions, choose the active one (P3.1), and export the active stops (P4a)."""

from __future__ import annotations

import json
from pathlib import Path

import typer
from sqlalchemy import text

from tda.cli_support import cli_errors, whoami
from tda.config.settings import get_settings
from tda.connectors.gtfs_static import GtfsStaticConnector, activate
from tda.metrics.feeds import ActiveFeed, Stop, active_feed, search_stops
from tda.store.db import writer_engine

gtfs_app = typer.Typer(
    help="GTFS feed versions: list them, choose the active one, and export its stops.", no_args_is_help=True
)
SOURCE = typer.Option(GtfsStaticConnector.source_id, "--source", help="The GTFS source id.")


@gtfs_app.command()
@cli_errors
def versions(source_id: str = SOURCE) -> None:
    """Current (not rolled-back) feed versions, newest first; `*` marks the active one."""
    engine = writer_engine(get_settings())
    try:
        with engine.connect() as connection:
            rows = connection.execute(
                text(
                    "SELECT id, feed_label, feed_start, feed_end, loaded_at, is_active, activated_by "
                    "FROM tda.current_gtfs_feed_version WHERE source_id = :s ORDER BY id DESC"
                ),
                {"s": source_id},
            ).all()
    finally:
        engine.dispose()
    for r in rows:
        mark = "*" if r.is_active else " "
        by = f" (activated by {r.activated_by})" if r.is_active else ""
        typer.echo(
            f"{mark} {r.id:>5}  {r.feed_start} .. {r.feed_end}  loaded {r.loaded_at:%Y-%m-%d %H:%M}Z  "
            f"{r.feed_label or '-'}{by}"
        )
    if not rows:
        typer.echo(f"no current feed versions for {source_id}")


@gtfs_app.command("activate")
@cli_errors
def activate_version(
    feed_version_id: int,
    source_id: str = SOURCE,
    by: str = typer.Option(None, "--by", help="Who is activating it (default: your user name)."),
) -> None:
    """Make a current feed version the active one (appends an activation; nothing is changed or deleted)."""
    engine = writer_engine(get_settings())
    try:
        with engine.begin() as connection:
            activate(connection, source_id, feed_version_id, by or whoami())
    finally:
        engine.dispose()
    typer.echo(f"feed version {feed_version_id} of {source_id} is now active")


FALLBACK = Path("src") / "app" / "data" / "stops.fallback.generated.ts"
FORMAT = typer.Option("ts", "--format", help="Output format; only ts (a TypeScript module) is supported.")
OUT = typer.Option(None, "--out", help=f"Where to write it (default: <repo>/{FALLBACK.as_posix()}).")


@gtfs_app.command("export-stops")
@cli_errors
def export_stops(fmt: str = FORMAT, out: Path | None = OUT, source_id: str = SOURCE) -> None:
    """Write the active feed's boardable stops (id, name, lat, lng) for the web app's fallback (P4b)."""
    if fmt != "ts":
        raise typer.BadParameter("only ts is supported", param_hint="--format")
    settings = get_settings()
    path = out or settings.project_root.parent / FALLBACK
    engine = writer_engine(settings)
    try:
        with engine.connect() as connection:
            feed = active_feed(connection, source_id)
            stops = search_stops(connection, feed, None, None, routes=False)
            attribution = connection.execute(
                text("SELECT attribution_text FROM tda.source WHERE id = :s"), {"s": feed.source_id}
            ).scalar_one_or_none()
    finally:
        engine.dispose()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_stops_ts(feed, stops, attribution), encoding="utf-8")
    typer.echo(f"wrote {len(stops)} stops from {feed.source_id} ({feed.feed_label or 'no label'}) to {path}")


def render_stops_ts(feed: ActiveFeed, stops: list[Stop], attribution: str | None) -> str:
    """A TypeScript module with every stop, in a stable order, so a regenerated file diffs cleanly."""
    lines = [
        "// Generated by `tda gtfs export-stops --format ts` (data_agent). Don't edit it: regenerate it",
        "// when the GTFS feed changes.",
        f"// Source: {_comment(feed.source_id)}, feed {_comment(feed.feed_label or '(no label)')}, "
        f"valid {feed.feed_start.isoformat()} to {feed.feed_end.isoformat()}.",
    ]
    if attribution:
        lines.append(f"// {_comment(attribution)}")
    lines += [
        "export type FallbackStop = { id: string; name: string; lat: number; lng: number };",
        "",
        "export const fallbackStops: readonly FallbackStop[] = [",
        *(
            f"  {{ id: {_js(stop.stop_id)}, name: {_js(stop.name or stop.stop_id)}, "
            f"lat: {stop.lat!r}, lng: {stop.lng!r} }},"
            for stop in stops
        ),
        "];",
        "",
    ]
    return "\n".join(lines)


def _js(value: str) -> str:
    """A JSON string literal, which is also a valid TypeScript one (line separators escaped too)."""
    return json.dumps(value, ensure_ascii=False).replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")


def _comment(value: str) -> str:
    """One line of comment text: every line break (LF, CR, U+2028, U+2029, ...) becomes a space."""
    return " ".join(value.split())
