/**
 * P4b: the committed stop data. The export-stops fallback must be either the explicit placeholder (no real export
 * yet) or a real export; fixture or synthetic output may never be committed as stops. Demo stops stay demo-only.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { DEMO_STOP_MAPPING_STATUS, demoScenarioStops } from '@/app/data/demo-stops';
import { busStopCoordinates } from '@/app/data/busStopCoordinates';
import { fallbackStops } from '@/app/data/stops.fallback.generated';
import { DEMO_SCENARIO_IDS } from '@/lib/demo/scenarios';
import { looksLikeFixture } from '@/lib/stops/catalog';

const fallbackSource = readFileSync(join(__dirname, '../../app/data/stops.fallback.generated.ts'), 'utf8');

describe('stops.fallback.generated.ts', () => {
  it('is the explicit placeholder while it is empty', () => {
    if (fallbackStops.length > 0) return;
    expect(fallbackSource).toMatch(/^\/\/ PLACEHOLDER: not generated\./);
  });

  it('once filled, is a real export-stops file, not fixture or synthetic output', () => {
    if (fallbackStops.length === 0) return;
    expect(fallbackSource).toMatch(/^\/\/ Generated by `tda gtfs export-stops --format ts`/);
    expect(fallbackSource).not.toMatch(/fixture|Test data|synthetic/i);
    expect(looksLikeFixture(fallbackStops)).toBe(false);
    for (const stop of fallbackStops) {
      expect(stop.id).not.toBe('');
      expect(Number.isFinite(stop.lat) && Number.isFinite(stop.lng)).toBe(true);
    }
  });

  it('exports the names the export-stops command writes, so a regenerated file drops in unchanged', () => {
    expect(fallbackSource).toContain('export type FallbackStop = { id: string; name: string; lat: number; lng: number };');
    expect(fallbackSource).toContain('export const fallbackStops: readonly FallbackStop[] = [');
  });
});

describe('demo-stops.ts', () => {
  it('covers every demo scenario', () => {
    expect(Object.keys(demoScenarioStops).sort()).toEqual([...DEMO_SCENARIO_IDS].sort());
  });

  it('uses the 05 §2b P0 keys with their coordinates, and maps the weekend scenario to Isle of Palms', () => {
    for (const { departure, destination } of Object.values(demoScenarioStops)) {
      for (const stop of [departure, destination]) {
        expect(busStopCoordinates[stop.key]).toEqual({ lat: stop.lat, lng: stop.lng });
      }
    }
    expect(demoScenarioStops.weekend.destination.key).toBe('Isle of Palms / 14th Avenue');
    expect(JSON.stringify(demoScenarioStops)).not.toMatch(/Folly/);
  });

  it('claims no GTFS stop id while 05 §2b is unsigned', () => {
    expect(DEMO_STOP_MAPPING_STATUS).toBe('pending_05_2b_signoff');
    for (const { departure, destination } of Object.values(demoScenarioStops)) {
      expect([departure.gtfsStopId, destination.gtfsStopId]).toEqual([null, null]);
    }
  });
});
