"""``tda gtfs export-stops --format ts`` (P4a task 7): the web app's offline stop list (active feed)."""

from __future__ import annotations

import re
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from typer.testing import CliRunner

from tda.cli import app
from tda.config.settings import get_settings
from tests.conftest import DbUrls
from tests.support.feeds import LoadFeed, edited

HEADER = [
    "// Generated by `tda gtfs export-stops --format ts` (data_agent). Don't edit it: regenerate it",
    "// when the GTFS feed changes.",
    "// Source: carta-gtfs, feed fixture-1, valid 2026-01-01 to 2026-12-31.",
    "// Test data",
    "export type FallbackStop = { id: string; name: string; lat: number; lng: number };",
    "",
    "export const fallbackStops: readonly FallbackStop[] = [",
]


@pytest.fixture
def invoke(db: DbUrls, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Iterator[Any]:
    monkeypatch.setenv("TDA_DATABASE_URL", db.writer)
    monkeypatch.setenv("TDA_PROJECT_ROOT", str(tmp_path / "data_agent"))
    runner = CliRunner()

    def run(*args: str) -> Any:
        get_settings.cache_clear()
        try:
            return runner.invoke(app, list(args), catch_exceptions=False)
        finally:
            get_settings.cache_clear()

    yield run


def test_it_writes_every_boardable_stop_to_the_default_path(
    invoke: Any, load_feed: LoadFeed, tmp_path: Path
) -> None:
    load_feed()
    result = invoke("gtfs", "export-stops", "--format", "ts")
    target = tmp_path / "src" / "app" / "data" / "stops.fallback.generated.ts"
    assert (
        result.exit_code == 0 and f"wrote 10 stops from carta-gtfs (fixture-1) to {target}" in result.stdout
    )
    lines = target.read_text(encoding="utf-8").splitlines()
    assert lines[: len(HEADER)] == HEADER
    assert lines[len(HEADER)] == '  { id: "FX01", name: "Fixture Stop 01", lat: 32.774, lng: -79.937 },'
    assert lines[-1] == "];" and len(lines) == len(HEADER) + 10 + 1


def test_names_are_escaped_as_string_literals(invoke: Any, load_feed: LoadFeed, tmp_path: Path) -> None:
    load_feed(edited(replace=[("stops.txt", "Fixture Stop 03", 'King\'s St \\ "East"')]))
    out = tmp_path / "stops.ts"
    assert invoke("gtfs", "export-stops", "--out", str(out)).exit_code == 0
    line = next(line for line in out.read_text(encoding="utf-8").splitlines() if '"FX03"' in line)
    assert line == '  { id: "FX03", name: "King\'s St \\\\ \\"East\\"", lat: 32.782, lng: -79.931 },'


def test_the_output_is_stable(invoke: Any, load_feed: LoadFeed, tmp_path: Path) -> None:
    load_feed()
    first, second = tmp_path / "a.ts", tmp_path / "b.ts"
    invoke("gtfs", "export-stops", "--out", str(first))
    invoke("gtfs", "export-stops", "--out", str(second))
    assert first.read_bytes() == second.read_bytes()


def test_only_ts_and_an_active_feed(invoke: Any, tmp_path: Path) -> None:
    other = invoke("gtfs", "export-stops", "--format", "json", "--out", str(tmp_path / "x"))
    # Typer may render usage errors in a colored panel (CI does), so compare the plain words only.
    plain = " ".join(re.sub(r"[│╭╮╰╯─]", " ", re.sub(r"\x1b\[[0-9;]*m", "", other.stderr)).split())
    assert other.exit_code == 2 and "only ts is supported" in plain
    none = invoke("gtfs", "export-stops", "--out", str(tmp_path / "x.ts"))
    assert none.exit_code == 2 and "error: no active GTFS feed for source carta-gtfs" in none.stderr
    assert not (tmp_path / "x.ts").exists()
